### ISSUE TITLE
what is osm-split?

### ISSUE THREAD

**Issue by morganherlocker** [mapbox/osm-tiler#1]
osm-split is intended to be a C++ tool using libosmium for efficiently splitting an OSM planet file into tiled chunks of either line-delimitted geojson or osm.pbf files, similar to most metro-extract tools. This allows the single-threaded memory-hungry operations required for processing the planet to be run only once, allowing mapreduce tools to perform additional transformations in JavaScript. 

osm-split will make a couple subjective decisions about the data that any processor could live with. For example, only OSM objects that can be joined to a node's lng/lat will be output. In the case of turn-restrictions, this would mean building an intermediate geometry from the from/via/to objects so that they can be tiled. Beyond these basic spatial operations necessary for indexing, osm-split would not perform any other filtering of tags, which allows a wide array of tile-reduce processors to use the data however they need to.
### Why not use existing extract tools?

Most of the existing extract tools allow for arbitrary polygons to be used to define areas of interest. This presents memory and computation challenges that we can easily sidestep with our use case, which is restricted to tiles. Generating a unique list of tiles that an OSM object overlaps with is significantly cheaper than performing the same operation for an arbitrary shape like a city boundary. Also, having tight control over how fuzzy OSM objects like relations are handled should give us a bit more flexibility over general-purpose tools like minjur.
### next steps:
- [x] [get code compiling from scratch with a basic Makefile setup](https://github.com/mapbox/osm-split/issues/2)
- [x] [write the tile indexing logic](https://github.com/mapbox/osm-split/issues/3)
- [x] [output to geojson option](https://github.com/mapbox/osm-split/issues/4)
- [ ] [output to osm.pbf option](https://github.com/mapbox/osm-split/issues/5)
- [ ] benchmark performance using leveldb as the node-cache
- [ ] if leveldb is too slow, switch to libosmiums RAM-based node-cache

cc @rclark @camilleanne
